/**********************************************************************
 * Extern for contentful
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var contentful = {
  "createClient": function (object) {}
};
var content = {
  "getEntry": function (object) {},
  "getEntries": function (object) {}
};
/**********************************************************************
 * End Generated Extern for contentful
/**********************************************************************/